import pandas as pd
df = pd.read_csv("Asia.csv").drop(['Unnamed: 0'], axis=1)
di = {"กทม":"Bangkok",
 "กระบี่":"Krabi",
 "กาญจนบุรี":"Kanchanaburi",
 "กาฬสินธุ์": "Kalasin",
 "ขอนแก่น":"Khon Kaen",
 "จันทบุรี":"Chanthaburi",
       "ฉะเชิงเทรา":"Chachoengsao",
 "ชลบุรี":"Chonburi",
 "ชัยภูมิ": "Chaiyaphum",
 "ชุมพร":"Chumphon",
 "เชียงราย":"Chiang Rai",
       "เชียงใหม่":"Chiang Mai",
 "ตรัง":"Trang",
 "ตาก":"Tak",
 "นครนายก":"Nakhon Nayok",
 "นครปฐม":"Nakhon Pathom",
 "นครพนม":"Nakhon Phanom",
       "นครราชสีมา":"Nakhon Ratchasima",
 "นครศรีธรรมราช":"Nakhon Si Thammarat",
 "นครสวรรค์":"Nakhon Sawan",
 "นนทบุรี":"Nonthaburi",
 "นราธิวาส":"Narathiwat",
       "บุรีรัมย์":"Buri Ram",
 "ปทุมธานี":"Pathum Thani",
 "ประจวบคีรีขันธ์":"Prachuap Khiri Khan",
 "ปราจีนบุรี":"Prachinburi",
       "ปัตตานี":"Pattani",
 "พระนครศรีอยุธยา":"Ayutthaya",
 "พะเยา":"Phayao",
 "พังงา":"Phang Nga",
 "พัทลุง":"Phatthalung",
       "พิษณุโลก":"Phitsanulok",
 "เพชรบุรี":"Phetchaburi",
 "เพชรบูรณ์":"Phetchabun",
 "แพร่":"Phrae",
 "ภูเก็ต":"Phuket",
 "มหาสารคาม":"Maha Sarakham ",
       "มุกดาหาร":"Mukdahan",
 "แม่ฮ่องสอน":"Mae Hong Son",
 "ไม่ทราบ":"ไม่ทราบ",
 "ยโสธร":"Yasothon",
 "ยะลา":"Yala",
 "ร้อยเอ็ด":"Roi Et",
       "ระยอง":"Rayong",
 "ราชบุรี":"Ratchaburi",
 "ลพบุรี":"Lopburi",
 "ลำปาง":"Lampang",
 "ลำพูน":"Lamphun",
 "เลย":"Loei",
 "ศรีสะเกษ":"Sisaket",
       "สกลนคร":"Sakon Nakhon",
 "สงขลา":"Songkhla",
 "สตูล":"Satun",
 "สมุทรปราการ":"Samut Prakan",
 "สมุทรสงคราม":"Samut Songkhram",
       "สมุทรสาคร":"Samut Sakhon",
 "สระแก้ว":"Sa Kaeo",
 "สระบุรี":"Saraburi",
 "สุโขทัย":"Sukhothai",
 "สุพรรณบุรี":"Suphanburi",
       "สุราษฎร์ธานี":"Surat Thani",
 "สุรินทร์":"Surin",
 "หนองคาย":"Nong Khai",
 "หนองบัวลำภู":"Nongbua Lamphu",
 "อำนาจเจริญ":"Amnat Charoen",
       "อุดรธานี":"Udon Thani",
 "อุตรดิตถ์":"Uttaradit",
 "อุทัยธานี":"Uthai Thani",
 "อุบลราชธานี":"Ubon Ratchathani",
 "北海道":"Hokkaido",
 "青森":"Aomori",
 "宮城":"Iwate",
 "宮城":"Miyagi",
 "秋田":"Akita",
 "山形":"Yamagata",
 "福島":"Fukushima",
 "茨城":"Ibaraki",
 "栃木":"Tochigi",
 "群馬":"Gunma",
 "埼玉":"Saitama",
 "千葉":"Chiba",
"東京":"Tokyo",
 "神奈川":"Kanagawa",
 "新潟":"Niigata",
 "富山":"Toyama",
 "石川":"Ishikawa",
 "福井":"Fukui",
 "山梨":"Yamanashi",
 "長野":"Nagano",
 "岐阜":"Gifu",
 "静岡":"Shizuoka",
 "愛知":"Aichi",
"三重":"Mie",
 "滋賀":"Shiga",
 "京都":"Kyoto",
 "大阪":"Osaka",
 "兵庫":"Hyogo",
 "奈良":"Nara",
 "和歌山":"Wakayama",
 "鳥取":"Tottori",
 "島根":"Shimane",
 "岡山":"Okayama",
 "広島":"Hiroshima",
"山口":"Yamaguchi",
 "徳島":"Tokushima",
 "香川":"Kagawa",
 "愛媛":"Ehime",
 "高知":"Kochi",
 "福岡":"Fukuoka",
 "佐賀":"Saga",
 "長崎":"Nagasaki",
 "熊本":"Kumamoto",
 "大分":"Oita",
 "宮崎":"Miyazaki",
"鹿児島":"Kagoshima",
 "沖縄":"Okinawa",
 "チャーター便":"Charter voli",
 "検疫職員":"Qarantina",
 "クルーズ船":"Cruise Ship"}
df = df.replace({"site": di})
df.to_csv("Asia.csv")



